name: Ktlint Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Grant execute permission for gradlew
        run: chmod +x app/gradlew

      - name: Run Ktlint
        run: |
          cd app
          ./gradlew ktlintCheck

      - name: Upload Ktlint reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-report
          path: app/build/reports/ktlint
